import logoPath from "@assets/generated_images/thehighgrader_logo.png";
import { Link } from "wouter";
import { ArrowLeft } from "lucide-react";

const sections = [
  {
    title: "1. Acceptance of Terms",
    content: [
      {
        heading: "Agreement",
        text: "By accessing or using TheHighGrader™ ('the Service'), you agree to be bound by these Terms of Service ('Terms'). If you do not agree to these Terms, please do not use the Service.",
      },
      {
        heading: "Updates",
        text: "We reserve the right to modify these Terms at any time. We will notify you of material changes via email or an in-app notice. Your continued use of the Service after changes are posted constitutes your acceptance of the updated Terms.",
      },
    ],
  },
  {
    title: "2. Eligibility",
    content: [
      {
        heading: "Age Requirements",
        text: "You must be at least 13 years of age to create an account and use the Service. If you are under 18, you represent that a parent or legal guardian has reviewed and agreed to these Terms on your behalf, or that you are using the Service through a school or educational institution that has agreed to these Terms.",
      },
      {
        heading: "Account Integrity",
        text: "You agree to provide accurate, current, and complete information when registering. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account.",
      },
    ],
  },
  {
    title: "3. Description of Service",
    content: [
      {
        heading: "Platform Overview",
        text: "TheHighGrader™ is an AI-powered educational platform offering features including but not limited to: AI tutoring, quiz generation, essay writing assistance, lecture note summarization, photo-based problem solving, and a teacher-facing class management and grading system.",
      },
      {
        heading: "AI-Generated Content",
        text: "Some content on the platform — including feedback, grades, suggestions, and explanations — is generated by artificial intelligence. AI-generated content is provided for educational guidance and should not be treated as authoritative or infallible. Always exercise your own judgment and consult qualified educators when appropriate.",
      },
      {
        heading: "Teacher Features",
        text: "Teachers using TheHighGrader™ can create classes, publish assignments, review AI-evaluated submissions, push grades, and manage a grade book. Teachers are responsible for ensuring their use of these features complies with applicable school, district, and legal policies.",
      },
    ],
  },
  {
    title: "4. User Conduct",
    content: [
      {
        heading: "Permitted Use",
        text: "You agree to use the Service solely for lawful educational purposes in accordance with these Terms.",
      },
      {
        heading: "Prohibited Conduct",
        text: "You agree not to: submit content that is illegal, harmful, defamatory, or infringes on the rights of others; attempt to circumvent or manipulate the AI grading system; share your account credentials with others; scrape, reverse-engineer, or copy the platform; or use the Service to harass, bully, or harm any person.",
      },
      {
        heading: "Academic Integrity",
        text: "AI tools are meant to supplement learning — not replace your own work. Misusing AI-generated content to commit academic dishonesty violates both these Terms and your school's honor code. TheHighGrader™ bears no responsibility for academic integrity violations by users.",
      },
    ],
  },
  {
    title: "5. Intellectual Property",
    content: [
      {
        heading: "Our Content",
        text: "All content, branding, software, algorithms, and design elements of TheHighGrader™ are owned by or licensed to us and are protected by copyright, trademark, and other intellectual property laws. You may not copy, reproduce, or distribute our content without written permission.",
      },
      {
        heading: "Your Content",
        text: "You retain ownership of the content you submit to the platform (essays, answers, etc.). By submitting content, you grant TheHighGrader™ a limited, non-exclusive, royalty-free license to process, store, and display your content solely to provide the Service to you and your educators.",
      },
      {
        heading: "Feedback",
        text: "If you provide feedback, suggestions, or ideas about the Service, you grant us the right to use such feedback without restriction or compensation.",
      },
    ],
  },
  {
    title: "6. Privacy",
    content: [
      {
        heading: "Privacy Policy",
        text: "Your use of the Service is also governed by our Privacy Policy, which is incorporated into these Terms by reference. Please review our Privacy Policy to understand our data practices.",
      },
    ],
  },
  {
    title: "7. Subscription & Payments",
    content: [
      {
        heading: "Free & Paid Plans",
        text: "TheHighGrader™ may offer both free and paid subscription tiers. Features available under each plan are described on our Pricing page. Paid plans are billed on a recurring basis (monthly or annually) as selected at checkout.",
      },
      {
        heading: "Billing",
        text: "By subscribing to a paid plan, you authorize us to charge your payment method on a recurring basis. All fees are in US dollars and are non-refundable except where required by law or as explicitly stated in our refund policy.",
      },
      {
        heading: "Cancellation",
        text: "You may cancel your subscription at any time. Cancellation takes effect at the end of the current billing period. You will retain access to paid features until that date.",
      },
      {
        heading: "Price Changes",
        text: "We may change subscription pricing with at least 30 days' notice. Continued use after a price change takes effect constitutes acceptance of the new pricing.",
      },
    ],
  },
  {
    title: "8. Disclaimers",
    content: [
      {
        heading: "As-Is Service",
        text: "The Service is provided 'as is' and 'as available' without warranties of any kind, express or implied. We do not warrant that the Service will be uninterrupted, error-free, or that AI-generated content will be accurate or complete.",
      },
      {
        heading: "Educational Purpose",
        text: "TheHighGrader™ is an educational aid and does not replace professional tutoring, certified instruction, or official academic assessment. Grades and feedback generated by the AI are for guidance purposes only and should be reviewed by a qualified educator before being treated as official.",
      },
    ],
  },
  {
    title: "9. Limitation of Liability",
    content: [
      {
        heading: "No Consequential Damages",
        text: "To the fullest extent permitted by law, TheHighGrader™ and its affiliates, officers, employees, and partners shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of or inability to use the Service.",
      },
      {
        heading: "Liability Cap",
        text: "Our total liability to you for any claims arising out of or relating to these Terms or the Service shall not exceed the amount you paid us in the twelve months preceding the claim, or $50, whichever is greater.",
      },
    ],
  },
  {
    title: "10. Termination",
    content: [
      {
        heading: "By You",
        text: "You may terminate your account at any time by contacting us or using account deletion features within the platform.",
      },
      {
        heading: "By Us",
        text: "We reserve the right to suspend or terminate your account at any time, with or without notice, if you violate these Terms, engage in abusive behavior, or for any other reason at our sole discretion. Upon termination, your right to access the Service ceases immediately.",
      },
    ],
  },
  {
    title: "11. Governing Law",
    content: [
      {
        heading: "Jurisdiction",
        text: "These Terms are governed by the laws of the State of Delaware, United States, without regard to conflict of law provisions. Any disputes arising from these Terms shall be resolved in the courts of Delaware, and you consent to personal jurisdiction in such courts.",
      },
    ],
  },
  {
    title: "12. Contact Us",
    content: [
      {
        heading: "Questions",
        text: "If you have questions about these Terms of Service, please contact us at: legal@thehighgrader.com",
      },
    ],
  },
];

export default function Terms() {
  return (
    <div className="min-h-screen bg-[#070706] text-white">
      {/* Nav */}
      <header className="border-b border-white/5 bg-[#070706]/90 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-5xl mx-auto px-5 sm:px-8 h-14 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2.5">
            <img src={logoPath} alt="TheHighGrader" className="w-7 h-7 rounded-lg object-cover" />
            <span className="font-bold text-[15px] text-white">TheHighGrader™</span>
          </Link>
          <Link href="/" className="flex items-center gap-1.5 text-[13px] text-white/40 hover:text-white/80 transition-colors">
            <ArrowLeft className="w-4 h-4" />
            Back
          </Link>
        </div>
      </header>

      {/* Hero */}
      <div className="border-b border-white/5 bg-gradient-to-b from-violet-950/20 to-transparent">
        <div className="max-w-5xl mx-auto px-5 sm:px-8 py-16 sm:py-20">
          <p className="text-[11px] font-bold uppercase tracking-widest text-violet-400/70 mb-3">Legal</p>
          <h1 className="text-4xl sm:text-5xl font-bold text-white mb-4">Terms of Service</h1>
          <p className="text-[15px] text-white/40 max-w-xl leading-relaxed">
            Please read these terms carefully before using TheHighGrader™. They govern your access to and use of our platform and services.
          </p>
          <p className="mt-6 text-[12px] text-white/25">
            Last updated: March 21, 2026 &nbsp;·&nbsp; Effective: March 21, 2026
          </p>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-5xl mx-auto px-5 sm:px-8 py-14 sm:py-20">
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-12">
          {/* Sidebar ToC */}
          <aside className="hidden lg:block">
            <p className="text-[11px] font-bold uppercase tracking-widest text-white/20 mb-4">Contents</p>
            <ul className="space-y-2">
              {sections.map((s) => (
                <li key={s.title}>
                  <a
                    href={`#${s.title.replace(/\s+/g, "-").toLowerCase()}`}
                    className="text-[12px] text-white/30 hover:text-white/70 transition-colors leading-relaxed block"
                  >
                    {s.title}
                  </a>
                </li>
              ))}
            </ul>
          </aside>

          {/* Body */}
          <div className="lg:col-span-3 space-y-12">
            {sections.map((section) => (
              <div key={section.title} id={section.title.replace(/\s+/g, "-").toLowerCase()}>
                <h2 className="text-[18px] font-semibold text-white mb-6 pb-3 border-b border-white/8">
                  {section.title}
                </h2>
                <div className="space-y-5">
                  {section.content.map((item) => (
                    <div key={item.heading}>
                      <h3 className="text-[13px] font-semibold text-violet-300/80 mb-1.5">{item.heading}</h3>
                      <p className="text-[14px] text-white/50 leading-relaxed">{item.text}</p>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="border-t border-white/5 bg-[#070706] py-8">
        <div className="max-w-5xl mx-auto px-5 sm:px-8 flex flex-col sm:flex-row items-center justify-between gap-3">
          <p className="text-[12px] text-white/20">
            © {new Date().getFullYear()} TheHighGrader™. All rights reserved.
          </p>
          <div className="flex items-center gap-6">
            <Link href="/privacy" className="text-[12px] text-white/20 hover:text-white/50 transition-colors">Privacy Policy</Link>
            <Link href="/terms" className="text-[12px] text-white/40 hover:text-white/70 transition-colors">Terms of Service</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
